#include <util/delay.h>
#include "Ultrasonic.h"
#include "DIO_Interface.h"
#include "icu.h"

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
volatile u8 g_flag = 0;      /* This flag is set when the high time is calculated */
volatile u8 g_edgeCount = 0; /* Variable to count the edges */
volatile u16 g_timeHigh = 0; /* This is the time in which the signal travels from HC-SR04 to object and returns to the module HC-SR-04 again */

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description :
 * Function responsible for initializing the ICU driver, setup the ICU call back function
 * and setup the direction for the trigger pin as output pin.
 */
void Ultrasonic_init(void) {
	/* Configure the ICU Driver with F_CPU/8 and wait for the RAISING edge at the beginning */
	ICU_ConfigType ICU_Configurations = { F_CPU_8, RAISING };
	ICU_init(&ICU_Configurations);

	/* Ultrasonic_edgeProcessing() is the CallBack Function called by the ICU Driver */
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/* The TRIGGER_PIN is the pin responsible for sending the Trigger pulse to the Ultrasonic Sensor */
	DIO_u8SetPinDirection(TRIGGER_PORT, TRIGGER_PIN, OUTPUT);
	DIO_u8SetPinValue(TRIGGER_PORT, TRIGGER_PIN, LOW);

}
/*
 * Description :
 * Function responsible for sending the Trigger pulse to the Ultrasonic Sensor.
 */
void Ultrasonic_Trigger(void) {
	/* Send a 20 microseconds pulse to the Ultrasonic Sensor through the TRIGGER_PIN */
	DIO_u8SetPinValue(TRIGGER_PORT, TRIGGER_PIN, HIGH);
	_delay_us(20);
	DIO_u8SetPinValue(TRIGGER_PORT, TRIGGER_PIN, LOW);
}
/*
 * Description :
 * Function responsible for sending the trigger pulse by using Ultrasonic_Trigger() function
 * and start the measurements by the ICU from this moment.
 */
float Ultrasonic_readDistance(void) {
    g_edgeCount = 0;
    g_flag = 0;
    g_timeHigh = 0;

    Ultrasonic_Trigger(); // Send pulse

    // Wait for echo (with timeout)
    u16 timeout = 0;
    while ((g_flag != 1) && (timeout < 30000)) {
        _delay_us(1);
        timeout++;
    }

    if (g_timeHigh < 116) return 2.0f; // Min distance (2.0 cm)
        return (float)g_timeHigh / 58.0f;
}
/*
 * Description :
 * This is the call back function called by the ICU driver, It is used to calculate
 * the high time (pulse time) generated by the Ultrasonic Sensor.
 */
void Ultrasonic_edgeProcessing(void) {
    g_edgeCount++;

    if (g_edgeCount == 1) {
        ICU_clearTimerValue();
        ICU_setEdgeDetectionType(FALLING);
    }
    else if (g_edgeCount == 2) {
        g_timeHigh = ICU_getInputCaptureValue();

        // Ignore pulses shorter than 116µs (=2cm)
        if (g_timeHigh >= 116) {
            g_flag = 1; // Valid pulse
        } else {
            g_timeHigh = 0; // Invalid (too close)
        }

        ICU_setEdgeDetectionType(RAISING);
        g_edgeCount = 0;
    }
}
